#!/bin/bash
D2RQ_ROOT="$( dirname "${BASH_SOURCE[0]}" )"
CP="$D2RQ_ROOT/target/classes"
SEP=':'
if [ $(uname -s | grep -ic 'cygwin\|mingw') -gt 0 ]; then SEP=';'; fi
for jar in "$D2RQ_ROOT"/target/dependency/*.jar
do
  if [ ! -e "$jar" ]; then continue; fi
  CP="$CP$SEP$jar"
done
LOGCONFIG=${LOGCONFIG:-file:$D2RQ_ROOT/src/main/resources/log4j.properties}
exec java -cp "$CP" -Xmx1G "-Dlog4j.configuration=${LOGCONFIG}" org.d2rq.cli.validate "$@"
